openapi: "3.0.3"

info:
  title: "device-manager API"
  version: "0.1.0"
  description: "Device discovery, lifecycle, and plugin management for the next-nac system."
  x-accord-status: stable

paths:
  /api/devices:
    get:
      summary: "List all managed devices"
      operationId: listDevices
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [online, offline, quarantined, unknown]
          description: "Filter by device status"
        - name: type
          in: query
          required: false
          schema:
            type: string
          description: "Filter by device type"
      responses:
        '200':
          description: "List of devices"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'

  /api/devices/{id}:
    get:
      summary: "Get device by ID"
      operationId: getDeviceById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "Unique identifier of the device"
      responses:
        '200':
          description: "Device details"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '404':
          description: "Device not found"

  /api/devices/discover:
    post:
      summary: "Trigger device discovery scan"
      operationId: triggerDiscovery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiscoveryRequest'
      responses:
        '202':
          description: "Discovery scan initiated"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiscoveryStatus'

components:
  schemas:
    Device:
      type: object
      properties:
        id:
          type: string
          description: "Unique device identifier"
        name:
          type: string
          description: "Device hostname or display name"
        type:
          type: string
          description: "Device type (e.g., switch, router, access-point)"
        ip_address:
          type: string
          description: "Device IP address"
        mac_address:
          type: string
          description: "Device MAC address"
        status:
          type: string
          enum: [online, offline, quarantined, unknown]
        last_seen:
          type: string
          format: date-time
      required:
        - id
        - type
        - status

    DiscoveryRequest:
      type: object
      properties:
        subnet:
          type: string
          description: "CIDR notation subnet to scan (e.g., 192.168.1.0/24)"
        protocols:
          type: array
          items:
            type: string
            enum: [snmp, ssh, rest]
          description: "Protocols to use for discovery"
      required:
        - subnet

    DiscoveryStatus:
      type: object
      properties:
        scan_id:
          type: string
        status:
          type: string
          enum: [running, completed, failed]
        started_at:
          type: string
          format: date-time
      required:
        - scan_id
        - status
