import React, { useState, useMemo } from 'react';
import { useApi } from '../hooks/useApi';

// ── Types (mirror server AnalyticsData) ─────────────────────────────────────

interface TokenBreakdown {
  inputTokens: number;
  outputTokens: number;
  cacheCreationTokens: number;
  cacheReadTokens: number;
}

interface ModelUsage {
  model: string;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheCreationTokens: number;
  costUsd: number;
}

interface AnalyticsRequestEntry {
  requestId: string;
  service: string;
  costUsd: number;
  numTurns: number;
  durationMs: number;
  timestamp: string;
  status: string;
  tokens?: TokenBreakdown;
  modelUsage?: ModelUsage[];
}

interface AnalyticsServiceAggregate {
  service: string;
  requestCount: number;
  totalCost: number;
  avgCost: number;
  totalTurns: number;
  avgTurns: number;
  completed: number;
  failed: number;
  tokens: TokenBreakdown;
}

interface AnalyticsDayEntry {
  date: string;
  totalCost: number;
  requestCount: number;
  avgCost: number;
}

interface AnalyticsData {
  totals: {
    totalRequests: number;
    totalCost: number;
    avgCost: number;
    avgTurns: number;
    successRate: number;
    tokens: TokenBreakdown;
  };
  byService: AnalyticsServiceAggregate[];
  byDay: AnalyticsDayEntry[];
  byModel: ModelUsage[];
  requests: AnalyticsRequestEntry[];
}

// ── Styles ──────────────────────────────────────────────────────────────────

const cardStyle: React.CSSProperties = {
  background: '#1e293b',
  border: '1px solid #334155',
  borderRadius: 8,
  padding: '16px 20px',
  flex: '1 1 0',
  minWidth: 140,
};

const cardLabel: React.CSSProperties = {
  color: '#94a3b8',
  fontSize: 11,
  textTransform: 'uppercase',
  letterSpacing: 0.5,
  marginBottom: 4,
};

const cardValue: React.CSSProperties = {
  color: '#f1f5f9',
  fontSize: 24,
  fontWeight: 700,
};

const thStyle: React.CSSProperties = {
  textAlign: 'left',
  padding: '8px 12px',
  color: '#94a3b8',
  borderBottom: '1px solid #334155',
  fontWeight: 600,
  fontSize: 12,
  cursor: 'pointer',
  userSelect: 'none',
};

const thStyleStatic: React.CSSProperties = {
  ...thStyle,
  cursor: 'default',
};

const tdStyle: React.CSSProperties = {
  padding: '6px 12px',
  color: '#cbd5e1',
  borderBottom: '1px solid #1e293b',
  fontSize: 13,
};

const sectionTitle: React.CSSProperties = {
  color: '#f1f5f9',
  fontSize: 15,
  fontWeight: 700,
  marginBottom: 12,
};

const panelStyle: React.CSSProperties = {
  background: '#1e293b',
  border: '1px solid #334155',
  borderRadius: 8,
  padding: 16,
};

// ── Helpers ─────────────────────────────────────────────────────────────────

function fmt$(v: number): string {
  return `$${v.toFixed(4)}`;
}

function fmtTokens(n: number): string {
  if (n === 0) return '0';
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return String(n);
}

function fmtDuration(ms: number): string {
  if (ms === 0) return '-';
  if (ms < 1000) return `${ms}ms`;
  const s = ms / 1000;
  if (s < 60) return `${s.toFixed(1)}s`;
  const m = s / 60;
  return `${m.toFixed(1)}m`;
}

function fmtPct(v: number): string {
  return `${(v * 100).toFixed(1)}%`;
}

function statusColor(status: string): string {
  if (status === 'completed') return '#4ade80';
  if (status === 'failed') return '#f87171';
  return '#fbbf24';
}

const TOKEN_TYPES = [
  { key: 'input' as const, field: 'inputTokens' as const, label: 'Input', color: '#3b82f6', desc: 'New (uncached) input tokens sent to the model' },
  { key: 'output' as const, field: 'outputTokens' as const, label: 'Output', color: '#8b5cf6', desc: 'Tokens generated by the model (reasoning + tool calls + text)' },
  { key: 'cacheRead' as const, field: 'cacheReadTokens' as const, label: 'Cache Read', color: '#22c55e', desc: 'Input tokens served from prompt cache (90% cheaper)' },
  { key: 'cacheCreation' as const, field: 'cacheCreationTokens' as const, label: 'Cache Creation', color: '#f59e0b', desc: 'Input tokens written to prompt cache (25% surcharge)' },
];

function tokenTotal(t: TokenBreakdown): number {
  return t.inputTokens + t.outputTokens + t.cacheCreationTokens + t.cacheReadTokens;
}

// ── Stacked Bar Component ───────────────────────────────────────────────────

function TokenBar({ tokens, height = 24 }: { tokens: TokenBreakdown; height?: number }) {
  const total = tokenTotal(tokens);
  if (total === 0) return <span style={{ color: '#475569', fontSize: 12 }}>-</span>;

  return (
    <div style={{ display: 'flex', height, borderRadius: 4, overflow: 'hidden', minWidth: 60 }}>
      {TOKEN_TYPES.map(t => {
        const val = tokens[t.field];
        if (val === 0) return null;
        const pct = (val / total) * 100;
        return (
          <div
            key={t.key}
            title={`${t.label}: ${fmtTokens(val)} (${fmtPct(val / total)})`}
            style={{
              width: `${pct}%`,
              background: t.color,
              minWidth: 2,
            }}
          />
        );
      })}
    </div>
  );
}

// ── Component ───────────────────────────────────────────────────────────────

type SortKey = 'service' | 'requestCount' | 'totalCost' | 'avgCost' | 'totalTurns' | 'avgTurns';

export function Analytics() {
  const { data, loading, error } = useApi<AnalyticsData>('/api/hub/analytics');
  const [sortKey, setSortKey] = useState<SortKey>('totalCost');
  const [sortAsc, setSortAsc] = useState(false);
  const [expandedReq, setExpandedReq] = useState<string | null>(null);

  const sortedServices = useMemo(() => {
    if (!data) return [];
    const arr = [...data.byService];
    arr.sort((a, b) => {
      const av = a[sortKey];
      const bv = b[sortKey];
      if (typeof av === 'string' && typeof bv === 'string') {
        return sortAsc ? av.localeCompare(bv) : bv.localeCompare(av);
      }
      if (typeof av === 'number' && typeof bv === 'number') {
        return sortAsc ? av - bv : bv - av;
      }
      return 0;
    });
    return arr;
  }, [data, sortKey, sortAsc]);

  const maxDailyCost = useMemo(() => {
    if (!data) return 0;
    return Math.max(...data.byDay.map(d => d.totalCost), 0.001);
  }, [data]);

  const handleSort = (key: SortKey) => {
    if (sortKey === key) setSortAsc(!sortAsc);
    else { setSortKey(key); setSortAsc(false); }
  };

  const sortIndicator = (key: SortKey) => sortKey !== key ? '' : sortAsc ? ' \u25B4' : ' \u25BE';

  if (loading) return <div style={{ padding: 32, color: '#64748b', textAlign: 'center' }}>Loading analytics...</div>;
  if (error) return <div style={{ padding: 32, color: '#f87171', textAlign: 'center' }}>Error: {error}</div>;
  if (!data) return null;

  const { totals, byDay, byModel, requests } = data;
  const { tokens } = totals;
  const totalTk = tokenTotal(tokens);
  const hasTokenData = totalTk > 0;
  const totalInputAll = tokens.inputTokens + tokens.cacheReadTokens + tokens.cacheCreationTokens;
  const cacheHitRate = totalInputAll > 0 ? tokens.cacheReadTokens / totalInputAll : 0;

  return (
    <div style={{ height: '100%', overflow: 'auto', padding: 20, background: '#0f172a' }}>

      {/* ── Section 1: Overview Cards ──────────────────────────────────── */}
      <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 24 }}>
        <div style={cardStyle}>
          <div style={cardLabel}>Total Cost</div>
          <div style={cardValue}>{fmt$(totals.totalCost)}</div>
        </div>
        <div style={cardStyle}>
          <div style={cardLabel}>Total Requests</div>
          <div style={cardValue}>{totals.totalRequests}</div>
        </div>
        <div style={cardStyle}>
          <div style={cardLabel}>Avg Cost / Req</div>
          <div style={cardValue}>{fmt$(totals.avgCost)}</div>
        </div>
        <div style={cardStyle}>
          <div style={cardLabel}>Avg Turns / Req</div>
          <div style={cardValue}>{totals.avgTurns.toFixed(1)}</div>
        </div>
        <div style={cardStyle}>
          <div style={cardLabel}>Success Rate</div>
          <div style={{ ...cardValue, color: totals.successRate >= 0.8 ? '#4ade80' : totals.successRate >= 0.5 ? '#fbbf24' : '#f87171' }}>
            {fmtPct(totals.successRate)}
          </div>
        </div>
        {hasTokenData && (
          <>
            <div style={cardStyle}>
              <div style={cardLabel}>Total Tokens</div>
              <div style={cardValue}>{fmtTokens(totalTk)}</div>
            </div>
            <div style={cardStyle}>
              <div style={cardLabel}>Cache Hit Rate</div>
              <div style={{ ...cardValue, color: cacheHitRate >= 0.5 ? '#22c55e' : '#f59e0b' }}>
                {fmtPct(cacheHitRate)}
              </div>
            </div>
          </>
        )}
      </div>

      {/* ── Section 2: Token Breakdown ────────────────────────────────── */}
      {hasTokenData && (
        <div style={{ marginBottom: 24 }}>
          <div style={sectionTitle}>Token Breakdown</div>

          {/* 4 token type cards */}
          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 12 }}>
            {TOKEN_TYPES.map(t => {
              const val = tokens[t.field];
              const pct = totalTk > 0 ? val / totalTk : 0;
              return (
                <div key={t.key} style={{ ...cardStyle, borderLeft: `3px solid ${t.color}` }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 6 }}>
                    <div style={{ width: 8, height: 8, borderRadius: 2, background: t.color, flexShrink: 0 }} />
                    <div style={cardLabel}>{t.label}</div>
                  </div>
                  <div style={{ color: '#f1f5f9', fontSize: 22, fontWeight: 700 }}>{fmtTokens(val)}</div>
                  <div style={{ color: '#64748b', fontSize: 12, marginTop: 2 }}>{fmtPct(pct)} of total</div>
                  <div style={{ color: '#475569', fontSize: 11, marginTop: 4 }}>{t.desc}</div>
                </div>
              );
            })}
          </div>

          {/* Global stacked bar */}
          <div style={panelStyle}>
            <div style={{ fontSize: 12, color: '#94a3b8', marginBottom: 8 }}>Distribution</div>
            <TokenBar tokens={tokens} height={32} />

            {/* Cache efficiency detail */}
            {totalInputAll > 0 && (
              <div style={{ marginTop: 12, paddingTop: 12, borderTop: '1px solid #334155', display: 'flex', gap: 24, flexWrap: 'wrap' }}>
                <div>
                  <span style={{ color: '#94a3b8', fontSize: 12 }}>Total Input (all types): </span>
                  <span style={{ color: '#f1f5f9', fontSize: 13, fontWeight: 600 }}>{fmtTokens(totalInputAll)}</span>
                </div>
                <div>
                  <span style={{ color: '#94a3b8', fontSize: 12 }}>Cached: </span>
                  <span style={{ color: '#22c55e', fontSize: 13, fontWeight: 600 }}>{fmtTokens(tokens.cacheReadTokens)}</span>
                </div>
                <div>
                  <span style={{ color: '#94a3b8', fontSize: 12 }}>Cache Warmup: </span>
                  <span style={{ color: '#f59e0b', fontSize: 13, fontWeight: 600 }}>{fmtTokens(tokens.cacheCreationTokens)}</span>
                </div>
                <div>
                  <span style={{ color: '#94a3b8', fontSize: 12 }}>Uncached: </span>
                  <span style={{ color: '#3b82f6', fontSize: 13, fontWeight: 600 }}>{fmtTokens(tokens.inputTokens)}</span>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* ── Section 3: Per-Model Breakdown ────────────────────────────── */}
      {byModel.length > 0 && (
        <div style={{ marginBottom: 24 }}>
          <div style={sectionTitle}>By Model</div>
          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 12 }}>
            {byModel.map(mu => {
              const modelTotal = mu.inputTokens + mu.outputTokens + mu.cacheReadTokens + mu.cacheCreationTokens;
              const modelTokens: TokenBreakdown = {
                inputTokens: mu.inputTokens,
                outputTokens: mu.outputTokens,
                cacheReadTokens: mu.cacheReadTokens,
                cacheCreationTokens: mu.cacheCreationTokens,
              };
              return (
                <div key={mu.model} style={{ ...panelStyle, flex: '1 1 300px', minWidth: 280 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
                    <div style={{ fontFamily: 'monospace', fontSize: 13, fontWeight: 600, color: '#f1f5f9' }}>
                      {mu.model.replace(/-\d{8}$/, '')}
                    </div>
                    <div style={{ fontSize: 14, fontWeight: 700, color: '#f1f5f9' }}>{fmt$(mu.costUsd)}</div>
                  </div>
                  <TokenBar tokens={modelTokens} height={20} />
                  <div style={{ display: 'flex', gap: 12, marginTop: 8, flexWrap: 'wrap' }}>
                    {TOKEN_TYPES.map(t => {
                      const val = modelTokens[t.field];
                      return (
                        <div key={t.key} style={{ fontSize: 11 }}>
                          <span style={{ color: t.color }}>{t.label}: </span>
                          <span style={{ color: '#cbd5e1' }}>{fmtTokens(val)}</span>
                          {modelTotal > 0 && <span style={{ color: '#475569' }}> ({fmtPct(val / modelTotal)})</span>}
                        </div>
                      );
                    })}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* ── Section 4: Per-Service Table ──────────────────────────────── */}
      <div style={{ marginBottom: 24 }}>
        <div style={sectionTitle}>By Service</div>
        <div style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: 8, overflow: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: 700 }}>
            <thead>
              <tr>
                <th style={thStyle} onClick={() => handleSort('service')}>Service{sortIndicator('service')}</th>
                <th style={thStyle} onClick={() => handleSort('requestCount')}>Requests{sortIndicator('requestCount')}</th>
                <th style={thStyle} onClick={() => handleSort('totalCost')}>Cost{sortIndicator('totalCost')}</th>
                <th style={thStyle} onClick={() => handleSort('totalTurns')}>Turns{sortIndicator('totalTurns')}</th>
                <th style={thStyleStatic}>Input</th>
                <th style={thStyleStatic}>Output</th>
                <th style={thStyleStatic}>Cache Read</th>
                <th style={thStyleStatic}>Cache Create</th>
                <th style={thStyleStatic}>Token Distribution</th>
              </tr>
            </thead>
            <tbody>
              {sortedServices.length === 0 && (
                <tr><td colSpan={9} style={{ ...tdStyle, color: '#64748b', textAlign: 'center' }}>No data</td></tr>
              )}
              {sortedServices.map(svc => (
                <tr key={svc.service}>
                  <td style={{ ...tdStyle, fontWeight: 600, color: '#f1f5f9' }}>{svc.service}</td>
                  <td style={tdStyle}>
                    {svc.requestCount}
                    <span style={{ color: '#64748b', fontSize: 11, marginLeft: 4 }}>({svc.completed}/{svc.failed})</span>
                  </td>
                  <td style={tdStyle}>{fmt$(svc.totalCost)}</td>
                  <td style={tdStyle}>{svc.totalTurns}</td>
                  <td style={{ ...tdStyle, color: '#3b82f6' }}>{fmtTokens(svc.tokens.inputTokens)}</td>
                  <td style={{ ...tdStyle, color: '#8b5cf6' }}>{fmtTokens(svc.tokens.outputTokens)}</td>
                  <td style={{ ...tdStyle, color: '#22c55e' }}>{fmtTokens(svc.tokens.cacheReadTokens)}</td>
                  <td style={{ ...tdStyle, color: '#f59e0b' }}>{fmtTokens(svc.tokens.cacheCreationTokens)}</td>
                  <td style={{ ...tdStyle, width: 120 }}>
                    <TokenBar tokens={svc.tokens} height={16} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* ── Section 5: Daily Cost Chart ───────────────────────────────── */}
      {byDay.length > 0 && (
        <div style={{ marginBottom: 24 }}>
          <div style={sectionTitle}>Daily Cost</div>
          <div style={panelStyle}>
            <div style={{ display: 'flex', alignItems: 'flex-end', gap: 4, height: 120 }}>
              {byDay.map(day => {
                const pct = (day.totalCost / maxDailyCost) * 100;
                return (
                  <div key={day.date} style={{ flex: '1 1 0', display: 'flex', flexDirection: 'column', alignItems: 'center', height: '100%', justifyContent: 'flex-end' }}
                    title={`${day.date}: ${fmt$(day.totalCost)} (${day.requestCount} req)`}>
                    <div style={{ fontSize: 10, color: '#94a3b8', marginBottom: 4 }}>{fmt$(day.totalCost)}</div>
                    <div style={{ width: '100%', maxWidth: 40, background: '#3b82f6', borderRadius: '4px 4px 0 0', height: `${Math.max(pct, 2)}%`, minHeight: 2 }} />
                  </div>
                );
              })}
            </div>
            <div style={{ display: 'flex', gap: 4, marginTop: 4 }}>
              {byDay.map(day => (
                <div key={day.date} style={{ flex: '1 1 0', textAlign: 'center', fontSize: 10, color: '#64748b' }}>{day.date.slice(5)}</div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* ── Section 6: Request History ────────────────────────────────── */}
      <div>
        <div style={sectionTitle}>Request History</div>
        <div style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: 8, overflow: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: 900 }}>
            <thead>
              <tr>
                <th style={thStyleStatic}>Request ID</th>
                <th style={thStyleStatic}>Service</th>
                <th style={thStyleStatic}>Status</th>
                <th style={thStyleStatic}>Cost</th>
                <th style={thStyleStatic}>Turns</th>
                <th style={thStyleStatic}>Input</th>
                <th style={thStyleStatic}>Output</th>
                <th style={thStyleStatic}>Cache Read</th>
                <th style={thStyleStatic}>Cache Create</th>
                <th style={thStyleStatic}>Duration</th>
                <th style={thStyleStatic}>Timestamp</th>
              </tr>
            </thead>
            <tbody>
              {requests.length === 0 && (
                <tr><td colSpan={11} style={{ ...tdStyle, color: '#64748b', textAlign: 'center' }}>No requests</td></tr>
              )}
              {requests.map(req => {
                const isExpanded = expandedReq === req.requestId;
                return (
                  <React.Fragment key={req.requestId}>
                    <tr
                      onClick={() => setExpandedReq(isExpanded ? null : req.requestId)}
                      style={{ cursor: req.modelUsage?.length ? 'pointer' : 'default' }}
                    >
                      <td style={{ ...tdStyle, fontFamily: 'monospace', fontSize: 12 }}>
                        {req.modelUsage?.length ? <span style={{ color: '#475569', marginRight: 4 }}>{isExpanded ? '\u25BE' : '\u25B8'}</span> : null}
                        {req.requestId}
                      </td>
                      <td style={tdStyle}>{req.service}</td>
                      <td style={{ ...tdStyle, color: statusColor(req.status), fontWeight: 600 }}>{req.status}</td>
                      <td style={tdStyle}>{req.costUsd > 0 ? fmt$(req.costUsd) : '-'}</td>
                      <td style={tdStyle}>{req.numTurns > 0 ? req.numTurns : '-'}</td>
                      <td style={{ ...tdStyle, color: '#3b82f6' }}>{req.tokens ? fmtTokens(req.tokens.inputTokens) : '-'}</td>
                      <td style={{ ...tdStyle, color: '#8b5cf6' }}>{req.tokens ? fmtTokens(req.tokens.outputTokens) : '-'}</td>
                      <td style={{ ...tdStyle, color: '#22c55e' }}>{req.tokens ? fmtTokens(req.tokens.cacheReadTokens) : '-'}</td>
                      <td style={{ ...tdStyle, color: '#f59e0b' }}>{req.tokens ? fmtTokens(req.tokens.cacheCreationTokens) : '-'}</td>
                      <td style={tdStyle}>{fmtDuration(req.durationMs)}</td>
                      <td style={{ ...tdStyle, fontSize: 12, color: '#94a3b8' }}>
                        {req.timestamp ? new Date(req.timestamp).toLocaleString() : '-'}
                      </td>
                    </tr>
                    {/* Expanded: per-model detail */}
                    {isExpanded && req.modelUsage && req.modelUsage.map(mu => (
                      <tr key={`${req.requestId}-${mu.model}`} style={{ background: '#0f172a' }}>
                        <td style={{ ...tdStyle, paddingLeft: 32, fontFamily: 'monospace', fontSize: 11, color: '#64748b' }}>
                          {mu.model.replace(/-\d{8}$/, '')}
                        </td>
                        <td style={tdStyle} />
                        <td style={tdStyle} />
                        <td style={{ ...tdStyle, fontSize: 12 }}>{mu.costUsd > 0 ? fmt$(mu.costUsd) : '-'}</td>
                        <td style={tdStyle} />
                        <td style={{ ...tdStyle, color: '#3b82f6', fontSize: 12 }}>{fmtTokens(mu.inputTokens)}</td>
                        <td style={{ ...tdStyle, color: '#8b5cf6', fontSize: 12 }}>{fmtTokens(mu.outputTokens)}</td>
                        <td style={{ ...tdStyle, color: '#22c55e', fontSize: 12 }}>{fmtTokens(mu.cacheReadTokens)}</td>
                        <td style={{ ...tdStyle, color: '#f59e0b', fontSize: 12 }}>{fmtTokens(mu.cacheCreationTokens)}</td>
                        <td style={tdStyle} />
                        <td style={tdStyle} />
                      </tr>
                    ))}
                  </React.Fragment>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
